const API_BASE_URL="https://itachi-mart.onrender.com";
const API_URL=`${API_BASE_URL}/api/products`;
const ORDER_API_URL=`${API_BASE_URL}/api/orders`;
let products=[],orders=[],editingProductId=null;
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("currentYear").textContent=new Date().getFullYear();document.getElementById("productForm").addEventListener("submit",saveProduct);document.getElementById("productSearch").addEventListener("input",renderProducts);document.getElementById("productFilter").addEventListener("change",renderProducts);document.getElementById("productSort").addEventListener("change",renderProducts);document.getElementById("orderSearch").addEventListener("input",renderOrders);document.getElementById("orderStatusFilter").addEventListener("change",renderOrders);document.getElementById("productImage").addEventListener("input",previewImage);document.getElementById("cancelEdit").addEventListener("click",()=>resetProductForm());document.getElementById("refreshAnalytics").addEventListener("click",refreshAll);setupNavigation();refreshAll()});
async function refreshAll(){await Promise.all([loadProducts(),loadOrders()]);updateDashboard();renderAnalytics()}
async function loadProducts(){setLoading("productsLoading",true);try{const r=await fetch(API_URL);if(!r.ok)throw Error();const data=await r.json();products=Array.isArray(data)?data:(Array.isArray(data.products)?data.products:[]);renderProducts()}catch(e){showToast("Product API is unavailable.")}finally{setLoading("productsLoading",false)}}
async function loadOrders(){setLoading("ordersLoading",true);try{const r=await fetch(ORDER_API_URL);if(!r.ok)throw Error();const data=await r.json();orders=Array.isArray(data)?data:(Array.isArray(data.orders)?data.orders:[]);renderOrders()}catch(e){showToast("Order API is unavailable.")}finally{setLoading("ordersLoading",false)}}
function renderProducts(){const body=document.getElementById("productsTableBody"),search=document.getElementById("productSearch").value.toLowerCase().trim(),cat=document.getElementById("productFilter").value,sort=document.getElementById("productSort").value;let list=products.filter(p=>(String(p.name||"").toLowerCase().includes(search)||String(p.description||"").toLowerCase().includes(search))&&(cat==="all"||p.category===cat));list.sort((a,b)=>sort==="name"?String(a.name).localeCompare(String(b.name)):sort==="priceLow"?a.price-b.price:sort==="priceHigh"?b.price-a.price:sort==="stockLow"?a.stock-b.stock:new Date(b.createdAt||0)-new Date(a.createdAt||0));body.innerHTML=list.map(p=>`<tr><td><div class="product-cell"><img src="${escapeHTML(p.image)}" alt="${escapeHTML(p.name)}" onerror="this.style.visibility='hidden'"><strong>${escapeHTML(p.name)}</strong></div></td><td><span class="badge">${escapeHTML(p.category)}</span></td><td>${formatPrice(p.price)}</td><td class="${p.stock===0?"stock-out":p.stock<5?"stock-low":""}">${p.stock}</td><td><div class="action-buttons"><button class="action-btn edit" onclick="editProduct('${p._id}')">Edit</button><button class="action-btn delete" onclick="deleteProduct('${p._id}')">Delete</button></div></td></tr>`).join("");document.getElementById("productsEmpty").hidden=list.length>0;updateProductCount(list.length)}
async function saveProduct(e){e.preventDefault();const product={name:productName.value.trim(),category:productCategory.value,price:Number(productPrice.value),stock:Number(productStock.value),image:productImage.value.trim(),description:productDescription.value.trim()};clearMessages();if(!product.name||!product.category||!product.image||!product.description||product.price<0||product.stock<0||Number.isNaN(product.price)||Number.isNaN(product.stock)){showError("Please fill all fields correctly.");return}const edit=!!editingProductId;try{const r=await fetch(edit?`${API_URL}/${editingProductId}`:API_URL,{method:edit?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(product)});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.message||"Request failed");showSuccess(edit?"Product updated successfully.":"Product added successfully.");showToast(edit?"Product updated.":"Product added.");resetProductForm(false);await loadProducts();updateDashboard();renderAnalytics()}catch(err){showError(err.message||"Could not save product.")}}
function editProduct(id){const p=products.find(x=>x._id===id);if(!p)return;editingProductId=id;productName.value=p.name||"";productCategory.value=p.category||"";productPrice.value=p.price??"";productStock.value=p.stock??"";productImage.value=p.image||"";productDescription.value=p.description||"";addProductButton.textContent="✓ Update Product";cancelEdit.hidden=false;previewImage();document.getElementById("add-product").scrollIntoView({behavior:"smooth"});showToast("Editing "+p.name)}
async function deleteProduct(id){const p=products.find(x=>x._id===id);if(!p||!confirm(`Delete "${p.name}"?`))return;try{const r=await fetch(`${API_URL}/${id}`,{method:"DELETE"});if(!r.ok)throw Error("Delete failed");showToast("Product deleted.");await loadProducts();updateDashboard();renderAnalytics()}catch(e){showToast(e.message||"Could not delete product.")}}
function resetProductForm(clear=true){editingProductId=null;document.getElementById("productForm").reset();addProductButton.textContent="＋ Add Product";cancelEdit.hidden=true;imagePreview.innerHTML="IMAGE PREVIEW";if(clear)clearMessages()}
function previewImage(){const url=productImage.value.trim();imagePreview.innerHTML=url?`<img src="${escapeHTML(url)}" alt="Preview" onerror="this.parentElement.innerHTML='IMAGE COULD NOT LOAD'">`:"IMAGE PREVIEW"}
function renderOrders(){const grid=ordersGrid,search=orderSearch.value.toLowerCase().trim(),status=orderStatusFilter.value;const list=orders.filter(o=>(String(o.customerName||"").toLowerCase().includes(search)||String(o.email||"").toLowerCase().includes(search)||String(o._id||"").toLowerCase().includes(search))&&(status==="all"||o.status===status));grid.innerHTML=list.map(o=>{const items=o.items||[];return `<article class="order-card"><div class="order-head"><div><div class="order-id">ORDER #${escapeHTML(String(o._id||"").slice(-8).toUpperCase())}</div><div class="order-customer">${escapeHTML(o.customerName||"Customer")}</div><div class="order-email">${escapeHTML(o.email||"")}</div></div><span class="badge status-${String(o.status||"Pending").toLowerCase()}">${escapeHTML(o.status||"Pending")}</span></div><div class="order-meta"><span class="order-total">${formatPrice(o.totalAmount)}</span><span class="order-date">${formatDate(o.createdAt)}</span></div><div class="order-items">${items.map(i=>`${escapeHTML(i.name)} × ${Number(i.quantity)}`).join("<br>")||"No item details"}</div><select class="status-select" onchange="updateOrderStatus('${o._id}',this.value)">${getStatusOptions(o.status)}</select></article>`}).join("");ordersEmpty.hidden=list.length>0}
async function updateOrderStatus(id,status){try{const r=await fetch(`${ORDER_API_URL}/${id}/status`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok)throw Error("Status update failed");const o=orders.find(x=>x._id===id);if(o)o.status=status;showToast("Order status updated.");renderOrders();updateDashboard();renderAnalytics()}catch(e){showToast(e.message||"Could not update order.")}}
function updateDashboard(){totalProducts.textContent=products.length;totalOrders.textContent=orders.length;pendingOrders.textContent=orders.filter(o=>String(o.status||"Pending").toLowerCase()==="pending").length;totalRevenue.textContent=formatPrice(orders.reduce((s,o)=>String(o.status||"").toLowerCase()==="cancelled"?s:s+Number(o.totalAmount||0),0))}
function renderAnalytics(){renderRevenueChart();renderStatusChart();renderTopProducts()}
function getDays(){const a=[],n=new Date();for(let i=6;i>=0;i--){const d=new Date(n);d.setHours(0,0,0,0);d.setDate(n.getDate()-i);a.push(d)}return a}
function renderRevenueChart(){const days=getDays(),values=days.map(day=>orders.reduce((s,o)=>{if(!o.createdAt||String(o.status).toLowerCase()==="cancelled")return s;const d=new Date(o.createdAt);return d.toDateString()===day.toDateString()?s+Number(o.totalAmount||0):s},0)),max=Math.max(...values,1);sevenDayRevenue.textContent=formatPrice(values.reduce((a,b)=>a+b,0));revenueChart.innerHTML=values.map((v,i)=>`<div class="bar-item"><em>${formatCompact(v)}</em><div class="bar" style="height:${Math.max(v/max*100,v?8:2)}%"></div><small>${days[i].toLocaleDateString("en-IN",{weekday:"short"})}</small></div>`).join("")}
function renderStatusChart(){const ss=["Pending","Processing","Shipped","Delivered","Cancelled"],cs=ss.map(s=>orders.filter(o=>String(o.status||"Pending").toLowerCase()===s.toLowerCase()).length),max=Math.max(...cs,1);statusChart.innerHTML=ss.map((s,i)=>`<div class="status-row"><span>${s}</span><div class="status-track"><div class="status-fill" style="width:${cs[i]/max*100}%"></div></div><strong>${cs[i]}</strong></div>`).join("")}
function renderTopProducts(){const totals={};orders.forEach(o=>{if(String(o.status||"").toLowerCase()==="cancelled")return;(o.items||[]).forEach(i=>totals[i.name]=(totals[i.name]||0)+Number(i.quantity||0))});const top=Object.entries(totals).sort((a,b)=>b[1]-a[1]).slice(0,5);topProducts.innerHTML=top.length?top.map(([n,q],i)=>`<div class="top-row"><span class="rank">0${i+1}</span><span class="top-name">${escapeHTML(n)}</span><span class="top-qty">${q} sold</span></div>`).join(""):`<div class="empty-state">No sales data yet.</div>`}
function updateProductCount(n=products.length){productCount.textContent=`${n} product${n===1?"":"s"}`}
function getStatusOptions(c){return["Pending","Processing","Shipped","Delivered","Cancelled"].map(s=>`<option value="${s}" ${s===c?"selected":""}>${s}</option>`).join("")}
function formatPrice(v){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(v||0))}
function formatCompact(v){return v>=100000?"₹"+(v/100000).toFixed(1)+"L":v>=1000?"₹"+(v/1000).toFixed(1)+"K":"₹"+Math.round(v)}
function formatDate(v){if(!v)return"Unknown date";const d=new Date(v);return Number.isNaN(d.getTime())?"Unknown date":d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function setLoading(id,x){document.getElementById(id).hidden=!x}function clearMessages(){successMessage.textContent="";errorMessage.textContent=""}function showSuccess(x){successMessage.textContent=x}function showError(x){errorMessage.textContent=x}
function showToast(x){toastMessage.textContent=x;adminToast.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>adminToast.classList.remove("show"),2500)}
function setupNavigation(){const links=document.querySelectorAll(".side-link");links.forEach(l=>l.addEventListener("click",()=>{links.forEach(x=>x.classList.remove("active"));l.classList.add("active")}))}
window.editProduct=editProduct;window.deleteProduct=deleteProduct;window.updateOrderStatus=updateOrderStatus;